name: Stations Human Diff

on:
  schedule:
    # Github limit actually is */10 * * * *
    # Every minute on workdays from 6h to 20h
    - cron: '* 6-20 * * 1-5'

jobs:
  stations_diff:
    runs-on: ubuntu-latest
    steps:
      - uses: trainline-eu/stations-human-diff@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
